### ISSUE TITLE
Plugin Start issue

### ISSUE THREAD

**Issue by macjl** [htool/signalk-polar-performance-plugin#7]
Hello,

I have this error when starting the plugin : 
```
Nov 12 14:32:52 error starting plugin: TypeError: Cannot read properties of undefined (reading 'twa')
Nov 12 14:32:52 TypeError: Cannot read properties of undefined (reading 'twa') at /home/node/.signalk/node_modules/signalk-polar-performance-plugin/plugin/index.js:603:37 at Array.forEach (<anonymous>) at csvToPolarObject (/home/node/.signalk/node_modules/signalk-polar-performance-plugin/plugin/index.js:548:16) at plugin.start (/home/node/.signalk/node_modules/signalk-polar-performance-plugin/plugin/index.js:108:17) at doPluginStart (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:305:20) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:490:21 at savePluginOptions (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:171:13) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:477:13 at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:149:13) at Route.dispatch (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:119:3) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at /usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:284:15 at Function.process_params (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:346:12) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:280:10) at Function.handle (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:175:3) 
```

And this is the configuration : 
```
{
  "configuration": {
    "beatAngle": false,
    "beatVMG": false,
    "targetTWA": false,
    "tackTrue": true,
    "optimumWindAngle": true,
    "VMG": true,
    "useSOG": true,
    "useSOGsource": "",
    "perfAdjust": 1,
    "dampingTWA": 1,
    "dampingTWS": 1,
    "dampingBSP": 1,
    "csvTable": "TWA\\TWS;0.0;5.0;10.0;15.0;20.0;25.0;30.0;35.0;40.0;45.0;50.0;55.0;60.0\n0.0;0.00;0.00;0.00;0.00;0.00;0.00;0.00;0.00;0.00;0.00;0.00;0.00;0.00\n5.0;0.00;0.20;0.85;1.92;2.21;2.23;2.21;2.03;1.34;0.55;0.14;0.04;0.00\n10.0;0.00;0.76;2.09;3.74;4.18;4.19;4.13;3.59;2.52;1.38;0.52;0.11;0.01\n15.0;0.00;2.09;4.06;5.76;6.28;6.32;5.96;5.06;3.85;2.60;1.46;0.58;0.04\n20.0;0.00;3.25;5.82;7.75;8.38;8.24;7.51;6.34;5.04;3.72;2.38;1.09;0.08\n25.0;0.00;4.02;7.16;9.61;10.40;9.86;8.78;7.42;6.00;4.55;3.04;1.50;0.12\n30.0;0.00;4.64;8.32;11.33;12.30;11.32;9.90;8.38;6.79;5.17;3.50;1.80;0.14\n35.0;0.00;5.30;9.50;12.88;14.04;12.67;10.96;9.23;7.46;5.66;3.85;1.99;0.17\n40.0;0.00;5.95;10.63;14.09;15.50;13.87;11.93;9.98;8.03;6.07;4.09;2.10;0.18\n45.0;0.00;6.48;11.53;14.78;16.60;14.78;12.70;10.60;8.50;6.40;4.30;2.20;0.18\n50.0;0.00;6.84;12.12;14.95;17.26;15.34;13.21;11.04;8.86;6.66;4.48;2.28;0.19\n55.0;0.00;7.08;12.40;14.92;17.57;15.65;13.50;11.29;9.07;6.84;4.60;2.36;0.20\n60.0;0.00;7.26;12.40;15.00;17.59;15.83;13.61;11.36;9.13;6.88;4.63;2.39;0.20\n65.0;0.00;7.44;12.28;15.36;17.56;16.06;13.70;11.42;9.16;6.91;4.68;2.42;0.20\n70.0;0.00;7.60;12.26;15.90;17.76;16.52;14.12;11.80;9.49;7.20;4.90;2.54;0.22\n75.0;0.00;7.74;12.60;16.54;18.44;17.41;15.14;12.78;10.38;7.93;5.42;2.84;0.24\n80.0;0.00;7.87;13.22;17.20;19.46;18.60;16.61;14.17;11.62;8.94;6.14;3.22;0.28\n85.0;0.00;8.00;13.97;17.86;20.44;19.90;18.16;15.55;12.77;9.83;6.74;3.52;0.30\n90.0;0.00;8.15;14.68;18.43;21.10;21.08;19.50;16.62;13.54;10.33;7.04;3.65;0.31\n95.0;0.00;8.21;15.20;18.97;21.56;22.13;20.64;17.45;14.06;10.63;7.18;3.70;0.31\n100.0;0.00;8.08;15.46;19.49;22.01;22.98;21.64;18.20;14.57;10.94;7.34;3.77;0.32\n105.0;0.00;7.75;15.42;19.97;22.51;23.56;22.39;18.82;15.07;11.32;7.60;3.90;0.34\n110.0;0.00;7.50;15.24;20.33;22.99;23.70;22.52;18.95;15.22;11.46;7.70;3.97;0.34\n115.0;0.00;7.26;15.10;20.46;23.33;23.26;21.71;18.25;14.68;11.08;7.46;3.86;0.34\n120.0;0.00;7.26;15.01;20.36;23.45;22.37;20.20;16.93;13.61;10.28;6.95;3.61;0.31\n125.0;0.00;7.33;14.93;20.12;23.33;21.37;18.66;15.60;12.54;9.48;6.42;3.35;0.30\n130.0;0.00;7.36;14.80;19.80;22.92;20.58;17.70;14.81;11.92;9.02;6.12;3.20;0.29\n135.0;0.00;7.27;14.53;19.44;22.36;20.04;17.24;14.46;11.90;8.86;6.01;3.16;0.29\n140.0;0.00;7.03;14.04;19.10;21.77;19.68;17.00;14.30;11.56;8.78;5.99;3.16;0.29\n145.0;0.00;6.61;13.27;18.80;21.23;19.39;16.76;14.10;11.41;8.69;5.93;3.13;0.29\n150.0;0.00;6.07;12.35;18.40;20.62;19.02;16.43;13.82;11.20;8.53;5.83;3.08;0.28\n155.0;0.00;5.48;11.39;17.75;19.73;18.37;15.95;13.44;10.90;8.30;5.66;2.99;0.26\n160.0;0.00;4.94;10.40;16.52;18.23;17.12;15.05;12.78;10.39;7.92;5.38;2.83;0.25\n165.0;0.00;4.51;9.22;14.22;15.53;14.76;13.26;11.47;9.46;7.28;4.99;2.63;0.23\n170.0;0.00;4.19;7.66;10.39;11.18;10.88;10.16;9.14;7.84;6.24;4.39;2.34;0.20\n175.0;0.00;3.30;5.20;5.66;5.95;6.02;5.98;5.71;5.18;4.34;3.18;1.74;0.14\n180.0;0.00;0.80;1.13;1.21;1.24;1.24;1.24;1.21;1.15;1.02;0.79;0.44;0.04"
  },
  "enabled": true
```

**Comment by rosinbum** [comment]
Me too

**Comment by htool** [comment]
This format works:
```
twa/tws;6;8;10;12;14;16;20
0;0;0;0;0;0;0;0
46.9;4.23;0;0;0;0;0;0
44.8;0;5.09;0;0;0;0;0
43.5;0;0;5.72;0;0;0;0
42.6;0;0;0;6.22;0;0;0
41.8;0;0;0;0;6.57;0;0
40.8;0;0;0;0;0;6.75;0
41.1;0;0;0;0;0;0;6.93
52;4.57;5.59;6.33;6.87;7.23;7.45;7.65
60;4.93;5.93;6.66;7.15;7.47;7.68;7.94
75;5.17;6.18;6.91;7.37;7.68;7.92;8.31
90;5.29;6.43;7.23;7.71;8.03;8.29;8.57
110;5.38;6.56;7.36;7.84;8.22;8.6;9.31
120;5.2;6.38;7.23;7.76;8.16;8.55;9.36
135;4.65;5.84;6.78;7.43;7.87;8.25;9.03
150;3.92;5.05;5.97;6.7;7.2;7.58;8.17
144.2;4.19;0;0;0;0;0;0
146.4;0;5.25;0;0;0;0;0
146.9;0;0;6.17;0;0;0;0
147.1;0;0;0;6.91;0;0;0
148.3;0;0;0;0;7.33;0;0
171.2;0;0;0;0;0;6.76;0
176.3;0;0;0;0;0;0;7.59
```
I've added it to the README.

**Comment by macjl** [comment]
The workaround provided works. Thanks!
